'use client';
import { useState } from 'react';
import type { Locale } from '@/lib/locale';
export function RagDemo({ locale }: { locale: Locale }) {
 const es = locale === 'es';
 const scenarios = es ? [
  {id:'release',label:'Respuesta con evidencia',question:'¿Quién revisa una publicación de Atlas?',answer:'El equipo de plataforma revisa el cambio y una persona responsable aprueba la publicación [1].',source:'[1] Manual ficticio de Atlas · Publicaciones · §2',excerpt:'Cada publicación requiere revisión del equipo de plataforma y aprobación de la persona responsable.',status:'Respuesta respaldada por el fragmento sintético.'},
  {id:'missing',label:'Evidencia insuficiente',question:'¿Cuántos clientes utilizan Atlas?',answer:'No hay evidencia suficiente en estos documentos para responder. Necesito una fuente que documente el número de clientes.',source:'Sin cita: los fragmentos disponibles no contienen esa cifra.',excerpt:'El manual describe la revisión de publicaciones; no incluye métricas de clientes.',status:'Respuesta retenida por falta de evidencia.'},
  {id:'error',label:'Fallo de recuperación',question:'¿Cuál es la política de revisión?',answer:'No se pudo recuperar evidencia. Revisa la fuente o vuelve a intentarlo antes de generar una respuesta.',source:'Sin cita: recuperación no disponible en este escenario simulado.',excerpt:'Fallo simulado del servicio de recuperación. No se ha realizado ninguna solicitud.',status:'Fallo simulado. No se generó una respuesta sin respaldo.'}
 ] : [
  {id:'release',label:'Grounded answer',question:'Who reviews an Atlas release?',answer:'The platform team reviews the change and a responsible owner approves the release [1].',source:'[1] Fictional Atlas handbook · Releases · §2',excerpt:'Every release requires platform team review and approval from the responsible owner.',status:'Answer supported by the synthetic excerpt.'},
  {id:'missing',label:'Missing evidence',question:'How many customers use Atlas?',answer:'These documents do not contain enough evidence to answer. I need a source that documents the customer count.',source:'No citation: the available excerpts do not contain that figure.',excerpt:'The handbook describes release review; it does not include customer metrics.',status:'Answer withheld because evidence is missing.'},
  {id:'error',label:'Retrieval failure',question:'What is the review policy?',answer:'Evidence could not be retrieved. Review the source or try again before generating an answer.',source:'No citation: retrieval is unavailable in this simulated scenario.',excerpt:'Simulated retrieval service failure. No request has been made.',status:'Simulated failure. No unsupported answer generated.'}
 ];
 const [selected,setSelected]=useState(0); const scenario=scenarios[selected];
 return <section className="rag-demo" aria-label={es ? 'Escenarios RAG sintéticos' : 'Synthetic RAG scenarios'}><div className="project-tabs" role="group" aria-label={es ? 'Elegir un escenario' : 'Choose a scenario'}>{scenarios.map((item,index)=><button type="button" key={item.id} aria-pressed={selected===index} aria-controls="rag-result" onClick={()=>setSelected(index)}>{item.label}</button>)}</div><div id="rag-result" className="rag-result"><p className="eyebrow">{es ? 'Pregunta predefinida' : 'Preset question'}</p><h2>{scenario.question}</h2><div className="rag-columns"><div><h3>{es ? 'Contexto recuperado (simulado)' : 'Retrieved context (simulated)'}</h3><blockquote>{scenario.excerpt}</blockquote><p className="evidence">{scenario.source}</p></div><div><h3>{es ? 'Respuesta predefinida' : 'Scripted answer'}</h3><p>{scenario.answer}</p></div></div></div><p className="rag-status" role="status" aria-live="polite" aria-atomic="true">{scenario.status}</p><noscript><p>{es ? 'Sin JavaScript se muestra el ejemplo respaldado. Los otros escenarios demuestran abstención por falta de evidencia y un fallo simulado de recuperación.' : 'Without JavaScript, the grounded example is shown. The other scenarios demonstrate missing-evidence abstention and a simulated retrieval failure.'}</p></noscript></section>;
}
