import Image from "next/image";
import Link from "next/link";
import { getPortfolio, localePath, type Locale } from "@/lib/i18n";
import { ProjectShowcase } from "@/components/studio/ProjectShowcase";
export default function Home({ locale }: { locale: Locale }) {
 const portfolio = getPortfolio(locale); const t = (en: string, es: string) => locale === "es" ? es : en;
    const { identity, enterpriseStory: enterprise, projects, teaching, strengths, links } = portfolio;
    return <main id="main" className="shell" data-content-version={portfolio.version}>
    <section className="hero" aria-labelledby="intro-title">
      <div><p className="eyebrow">{identity.targetRole} · {t("Applied AI", "IA aplicada")}</p><h1 id="intro-title">{t("Thoughtful interfaces.", "Interfaces bien pensadas.")}<br /><span>{t("Serious engineering.", "Ingeniería con rigor.")}</span></h1><p className="hero-intro">{identity.intro}</p><div className="actions"><Link className="button" href="#work">{t("Explore my work", "Explorar mi trabajo")} <span aria-hidden="true">↘</span></Link><a className="button secondary" href={links.resume} download>{t("Download r\u00e9sum\u00e9", "Descargar CV")} <span aria-hidden="true">↓</span></a></div><p className="current-role">{t("Currently", "Actualmente")} {identity.currentRole} · {identity.currentCompany}</p></div>
      <ProjectShowcase locale={locale} projects={projects.map(({ id, name, image, imageAlt, evidenceLabel, previewExplanation, summary }) => ({ id, name, image, imageAlt, evidenceLabel, previewExplanation, summary }))}/>
    </section>
    <section className="career-snapshot" aria-label={t("Career at a glance", "Trayectoria de un vistazo")}>{portfolio.roles.slice(0,3).map(role=><Link href={localePath(locale, `/experience#role-${role.id}`)} key={role.id}><span>{role.positions.length > 1 ? `${role.positions.at(-1)!.period.split(' – ')[0]} – ${role.positions[0].period.split(' – ')[1]}` : role.positions[0].period}</span><strong>{role.company}</strong><p>{role.positions[0].title}</p></Link>)}</section><p className="career-summary">{identity.summary}</p>
    <section id="work" className="section" aria-labelledby="enterprise-heading"><div className="section-heading"><div><p className="eyebrow">{t("01 / Enterprise experience", "01 / Experiencia empresarial")}</p><h2 id="enterprise-heading">{t("Build the product.", "Construir el producto.")}<br />{t("Strengthen the platform.", "Fortalecer la plataforma.")}</h2></div><p>{t("Hands-on delivery and technical direction, working with engineers, Product and Design.", "Desarrollo y dirección técnica en colaboración con Ingeniería, Producto y Diseño.")}</p></div><div className="enterprise"><div><p className="eyebrow">{enterprise.company} · Lead Software Engineer</p><h3 className="enterprise-title">{enterprise.title}</h3><p>{enterprise.problem}</p><Link className="text-link" href={localePath(locale, `/work/${enterprise.id}`)}>{t("Read the contribution story \u2197", "Ver mi contribución ↗")}</Link></div><div className="contribution"><p className="eyebrow">{t("My contribution", "Mi contribución")}</p><p>{enterprise.contribution}</p><p className="eyebrow">{t("Delivered with the team", "Resultados con el equipo")}</p><p>{enterprise.outcome}</p></div></div></section>
    <section className="section" aria-labelledby="projects-heading"><div className="section-heading"><div><p className="eyebrow">{t("02 / Independent work", "02 / Proyectos independientes")}</p><h2 id="projects-heading">{t("Ideas, made inspectable.", "Ideas que puedes examinar.")}</h2></div><p>{t("Three projects where I connect frontend decisions with accessibility, agent coordination and verifiable results.", "Tres proyectos que conectan decisiones frontend con accesibilidad, coordinación de agentes y resultados verificables.")}</p></div><div className="project-list">{projects.map((project, index) => <Link className="project-row" key={project.id} href={localePath(locale, `/work/${project.id}`)}><span className="mono">0{index + 1}</span><div><h3>{project.name}</h3><p className="project-tech">{project.discipline}</p></div><div className="project-description"><p>{project.summary}</p></div><span className="arrow" aria-hidden="true">↗</span></Link>)}</div></section>
    <section className="section leadership" aria-labelledby="leadership-heading"><div><p className="eyebrow">{t("03 / Engineering leadership", "03 / Liderazgo técnico")}</p><h2 id="leadership-heading">{teaching.title}</h2></div><div className="leadership-copy"><p>{teaching.summary}</p><p>{t("My approach pairs explicit acceptance criteria with reviewable work. The goal is to help engineers reason about the output, including when the evidence is missing.", "Combino criterios de aceptación explícitos con trabajo que se puede revisar. Ayudo a los ingenieros a evaluar los resultados, incluso cuando falta evidencia.")}</p><Link className="text-link" href={localePath(locale, "/notes/evidence-before-completion")}>{t("Explore a public teaching exercise \u2197", "Explorar un ejercicio público ↗")}</Link></div></section>
    <section id="about" className="section about" aria-labelledby="about-heading"><div className="portrait"><Image src={identity.portrait} alt={identity.portraitAlt} fill sizes="(max-width:760px) 330px, 32vw"/></div><div className="about-copy"><p className="eyebrow">{t("04 / The engineer behind the work", "04 / El ingeniero detrás del trabajo")}</p><h2 id="about-heading">{t("I care about the interface.", "Me importa la interfaz.")}<br />{t("And what makes it work.", "Y lo que la hace funcionar.")}</h2><p>{identity.summary} {t("I work across implementation, shared architecture and the practices that help teams maintain their software.", "Trabajo en implementación, arquitectura compartida y prácticas para mantener el software en equipo.")}</p><p>{portfolio.rag.summary} {t("Public project stories focus on inspectable behavior and make their evidence limits explicit.", "Las historias públicas muestran comportamientos observables y explican los límites de su evidencia.")} <Link className="text-link" href={localePath(locale, "/work/rag")}>{t("Explore the synthetic RAG walkthrough ↗", "Explorar la demostración RAG sintética ↗")}</Link></p><div className="strengths">{strengths.map(group => <div key={group.title}><h3>{group.title}</h3><p>{group.items.join(" · ")}</p></div>)}</div><Link className="text-link" href={localePath(locale, "/experience")}>{t("Explore my full experience \u2197", "Ver toda mi experiencia ↗")}</Link></div></section>
    <section className="contact" id="contact" aria-labelledby="contact-heading"><div><p className="eyebrow">{t("Let\u2019s talk", "Hablemos")}</p><h2 id="contact-heading">{t("Have a hard frontend problem?", "¿Un reto complejo de frontend?")}</h2><p>{t("I\u2019m interested in Staff / Principal Frontend opportunities with applied AI depth.", "Busco oportunidades de Staff / Principal Frontend Engineer con profundidad en IA aplicada.")}</p></div><div className="actions"><a className="button" href={links.email}>{t("Email Jorge", "Escribir a Jorge")} <span aria-hidden="true">↗</span></a></div></section>
  </main>;
}
