import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getPortfolio, localePath, type Locale } from "@/lib/i18n";
export default function WorkStory({ locale, slug }: { locale: Locale; slug: string }) {
 const portfolio = getPortfolio(locale); const t = (en: string, es: string) => locale === "es" ? es : en;
    const project = portfolio.projects.find(item => item.id === slug);
    const enterprise = portfolio.enterpriseStory;
    if (slug === enterprise.id)
        return <main id="main" className="shell" data-content-version={portfolio.version}><header className="page-heading"><Link className="text-link" href={localePath(locale, "/#work")}>{t("\u2190 Selected work", "← Proyectos seleccionados")}</Link><p className="eyebrow" style={{ marginTop: 30 }}>{t("Enterprise contribution", "Contribución empresarial")} / {enterprise.company}</p><h1>{enterprise.title}</h1><p>{enterprise.contribution}</p><div className="tag-list">{enterprise.technologies.map(tech => <span key={tech}>{tech}</span>)}</div></header><StorySection title={t("Context", "Contexto")}><p>{enterprise.problem}</p><p>{enterprise.constraints}</p></StorySection><StorySection title={t("My contribution", "Mi contribución")}><p>{enterprise.contribution}</p></StorySection><StorySection title={t("Decision & tradeoff", "Decisión y compromiso")}><p>{enterprise.decision}</p><p>{enterprise.tradeoff}</p></StorySection><StorySection title={enterprise.artifactTitle}><p className="figure-caption">{enterprise.artifactSource}</p><p>{enterprise.artifactDecision}</p><p><strong>{t("Documented result.", "Resultado documentado.")}</strong> {enterprise.artifactResult}</p><p className="figure-caption">{enterprise.artifactBoundary}</p><a className="text-link" href={enterprise.artifactDownload} download>{t("Download the contribution record \u2193", "Descargar el registro de contribución ↓")}</a></StorySection><StorySection title={t("Result & evidence", "Resultado y evidencia")}><p>{enterprise.outcome}</p><p>{enterprise.limits}</p><Link className="text-link" href={localePath(locale, "/experience")}>{t("Read the full career history \u2197", "Ver toda la trayectoria ↗")}</Link></StorySection></main>;
    if (!project)
        notFound();
    const story = project.story;
    return <main id="main" className="shell" data-content-version={portfolio.version}><header className="page-heading"><Link className="text-link" href={localePath(locale, "/#work")}>{t("\u2190 Selected work", "← Proyectos seleccionados")}</Link><p className="eyebrow" style={{ marginTop: 30 }}>{t("Independent project", "Proyecto independiente")} / {project.name}</p><h1>{story.title}</h1><p>{project.summary}</p><div className="tag-list">{project.technologies.map(tech => <span key={tech}>{tech}</span>)}</div></header><figure><a className={`case-image project-image-${project.id}`} style={{ display: "block" }} href={project.fullImage} aria-label={t(`Open full ${project.name} application capture`, `Abrir captura completa de ${project.name}`)}><Image src={project.fullImage} alt={project.imageAlt} fill sizes="(max-width: 760px) 95vw, 85vw" priority/></a><figcaption className="figure-caption">{project.evidenceLabel} <a href={project.fullImage}>{t("View full capture \u2197", "Ver captura completa ↗")}</a></figcaption></figure><StorySection title={t("The problem", "El problema")}><p>{story.problem}</p></StorySection><StorySection title={t("What I built", "Lo que construí")}><p>{project.contribution}</p></StorySection><StorySection title={t("Decision & tradeoff", "Decisión y compromiso")}><p>{story.decision}</p><p>{story.tradeoff}</p></StorySection>
    {project.id === "evalgate" ? <StorySection title={portfolio.architecture.title}><figure className="diagram"><a href={portfolio.architecture.image}><Image src={portfolio.architecture.image} alt={t("Evalgate: define a check, execute a verifier, retain passing or failing results for review.", "Evalgate: definir una comprobación, ejecutar un verificador y conservar resultados para revisión.")} width={1120} height={680}/></a><figcaption className="figure-caption"><a href={portfolio.architecture.image}>{t("Open full architecture diagram \u2197", "Abrir el diagrama completo ↗")}</a></figcaption></figure><ol className="diagram-steps"><li><strong>{t("Constraint:", "Restricción:")}</strong> {portfolio.architecture.constraint}</li><li><strong>{t("Decision:", "Decisión:")}</strong> {portfolio.architecture.decision}</li><li><strong>{t("Result:", "Resultado:")}</strong> {portfolio.architecture.result}</li></ol><p>{portfolio.architecture.scope} {t("Retry counts are advisory; model judgments differ from deterministic checks.", "El número de reintentos es orientativo; la evaluación de un modelo difiere de las comprobaciones deterministas.")}</p></StorySection> : <StorySection title={t("How the workflow fits", "Cómo funciona el flujo")}><ol className="diagram-steps">{story.flow.map(step => <li key={step.title}><strong>{step.title}.</strong> {step.body}</li>)}</ol></StorySection>}
    <StorySection title={t("Explore the implementation", "Explorar la implementación")}><p>{story.captureBoundary}</p><div className="story-steps">{story.steps.map((step,index)=><details key={step.title} open={index===0}><summary>{index+1}. {step.title}</summary><p>{step.body}</p>{step.image ? <a href={step.image.startsWith("/") ? step.image : `/assets/${step.image}`}><Image className="story-step-image" src={step.image.startsWith("/") ? step.image : `/assets/${step.image}`} alt={step.alt ?? step.title} width={1200} height={760}/></a> : null}</details>)}</div></StorySection><StorySection title={t("Result & limits", "Resultado y límites")}><p>{project.outcome}</p><p>{story.limits}</p><a className="text-link" href={project.github}>{t("Inspect", "Explorar")} {project.name} {t("on GitHub", "en GitHub")} ↗</a></StorySection><section className="contact"><div><p className="eyebrow">{t("More engineering stories", "Más historias de ingeniería")}</p><div className="actions">{portfolio.projects.filter(item => item.id !== project.id).map(item => <Link className="button secondary" href={localePath(locale, `/work/${item.id}`)} key={item.id}>{item.name} ↗</Link>)}</div></div></section></main>;
}
function StorySection({ title, children }: {
    title: string;
    children: React.ReactNode;
}) { return <section className="case-grid"><h2>{title}</h2><div className="prose">{children}</div></section>; }
